module.exports = `
  type Query {
    helloworld: HelloWorld
    banks: [Bank!]
    bank(id: ID!): Bank
    users: [User!]
    user(id: ID!): User
    transactions: [Transaction!]
    transaction(id: ID!): Transaction
  }
`;
